services:
  postgres:
    container_name: postgres_server_container
    image: postgres:17.0
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'changeme'
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.12
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: 'pgadmin@example.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
    postgres:
        driver: bridge
